#!/bin/bash
# Rowan's Battle of Britain — Linux Port: end-user install script.
#
# Adapted from the FreeFalcon Linux port's packaging/install.sh. The engine is built
# from source here; the GAME DATA IS NOT REDISTRIBUTABLE, so the user brings their own
# install — in practice a Wine `drive_c` tree containing
#   <drive_c>/Program Files/Rowan Software/Battle Of Britain/
#
# Usage:
#   packaging/install.sh --drive-c /path/to/WP/drive_c [--prefix ~/.local]
#   packaging/install.sh --data   "/path/to/.../Battle Of Britain" [--prefix ~/.local]
#
# What it does:
#   1. Verifies the engine is built (32-bit i386 ELF) and the data dir looks like BoB.
#   2. Checks i386 runtime shared-library dependencies and reports any that are missing.
#   3. Installs a `bob` launcher + a .desktop entry into the prefix.
#
# KNOWN LIMITATION — see packaging/README.md "Relocatability": the build currently reads
# BOB.RC / F_GRAFIX.G from the SOURCE tree at runtime (compiled-in BOB_SRC_DIR), so the
# launcher pins BOB_RC_DIR back at this checkout. An installed copy is therefore NOT
# self-contained yet.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN="$REPO/build/bob"
DRIVE_C=""
DATA=""
PREFIX="$HOME/.local"

while [ $# -gt 0 ]; do
  case "$1" in
    --drive-c) DRIVE_C="$2"; shift 2 ;;
    --data)    DATA="$2";    shift 2 ;;
    --prefix)  PREFIX="$2";  shift 2 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

err() { echo "ERROR: $*" >&2; exit 1; }

# --- 1. preflight ----------------------------------------------------------
[ -x "$BIN" ] || err "engine not built: $BIN  (run: cmake -S . -B build -G Ninja && ninja -C build bob)"

case "$(file -b "$BIN" 2>/dev/null)" in
  *"ELF 32-bit"*"Intel 80386"*) : ;;
  *) echo "!! WARNING: $BIN does not look like a 32-bit i386 ELF — the port is i386-only." ;;
esac

# Accept either the drive_c root or the game dir itself; derive the other.
if [ -n "$DRIVE_C" ]; then
  DRIVE_C="$(cd "$DRIVE_C" 2>/dev/null && pwd)" || err "drive_c not found: $DRIVE_C"
  [ -n "$DATA" ] || DATA="$DRIVE_C/Program Files/Rowan Software/Battle Of Britain"
fi
[ -n "$DATA" ] || err "pass --drive-c /path/to/WP/drive_c (or --data '<...>/Battle Of Britain')"
DATA="$(cd "$DATA" 2>/dev/null && pwd)" || err "game dir not found: $DATA"
if [ -z "$DRIVE_C" ]; then
  # walk up to the last '/drive_c' ancestor, matching bob_main.cpp's own derivation
  d="$DATA"
  while [ "$d" != "/" ] && [ "$(basename "$d")" != "drive_c" ]; do d="$(dirname "$d")"; done
  [ "$d" != "/" ] || err "could not derive drive_c from '$DATA' — pass --drive-c explicitly"
  DRIVE_C="$d"
fi

# A BoB data tree has the numbered-file .DIR indexes at its root.
[ -f "$DATA/ROOTS.DIR" ] || [ -d "$DATA/MUSIC" ] || \
  err "'$DATA' has no ROOTS.DIR / MUSIC — not a Battle of Britain install?"

echo ">> engine:  $BIN"
echo ">> data:    $DATA"
echo ">> drive_c: $DRIVE_C"
echo ">> prefix:  $PREFIX"

# --- 2. runtime dependency check (i386!) -----------------------------------
# ldd on a 32-bit binary resolves against /usr/lib/i386-linux-gnu; a box with only the
# amd64 runtimes installed will show every library as "not found".
echo ">> checking i386 runtime libraries..."
MISSING="$(ldd "$BIN" 2>/dev/null | awk '/not found/{print $1}')"
if [ -n "$MISSING" ]; then
  echo "!! Missing 32-bit shared libraries:"
  echo "$MISSING" | sed 's/^/     /'
  echo "   On Debian/Ubuntu:"
  echo "     sudo dpkg --add-architecture i386 && sudo apt-get update"
  echo "     sudo apt-get install libsdl2-2.0-0:i386 libgl1:i386 libopenal1:i386 \\"
  echo "                          libfluidsynth3:i386 libstdc++6:i386"
  echo "   Music also wants a General MIDI SoundFont: apt-get install fluid-soundfont-gm"
  echo "   (or set BOB_SOUNDFONT=/path/to/bank.sf2; without one the game runs silent)."
else
  echo ">> all shared libraries resolve."
fi

# --- 3. launcher + desktop entry -------------------------------------------
mkdir -p "$PREFIX/bin" "$PREFIX/share/applications"
LAUNCHER="$PREFIX/bin/bob"
cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Generated by packaging/install.sh — Rowan's Battle of Britain (Linux port)
# The engine expects cwd == the install dir (FileMan's "." root) and derives
# BOB_DRIVE_C from the cwd's drive_c ancestor; both are pinned here explicitly.
cd "$DATA" || exit 1
export BOB_DRIVE_C="\${BOB_DRIVE_C:-$DRIVE_C}"
# NOT relocatable yet: the runtime .rc / F_GRAFIX.G parser reads the source checkout
# (compiled-in BOB_SRC_DIR; BOB_RC_DIR is the runtime override).
export BOB_RC_DIR="\${BOB_RC_DIR:-$REPO/SRC}"
exec "$BIN" "\$@"
EOF
chmod +x "$LAUNCHER"
echo ">> installed launcher: $LAUNCHER"

cat > "$PREFIX/share/applications/bob.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Battle of Britain (Linux Port)
Comment=Rowan's Battle of Britain (2000) — native Linux port
Exec=$LAUNCHER
Terminal=false
Categories=Game;Simulation;
EOF
echo ">> installed desktop entry"

echo
echo "Done. Run with:  $LAUNCHER            (ensure $PREFIX/bin is on your PATH)"
echo "Front-end:       BOB_FRONTEND=1 BOB_OLE_DRAW=1 $LAUNCHER"
echo "Flight:          BOB_BOOT_FRONTEND=1 $LAUNCHER   (needs a real GL display)"
