#!/usr/bin/env python3
"""BOB-KEYMAP-1: Battle of Britain keyboard map from the game's own live key table.

Source of truth: KeyMap3d::mappings[scancode][shiftstate] AFTER Reg3dConv has loaded the game's
table, written by BOB_DUMP_BINDINGS=<path> (SRC/MFC/STUB3D.CPP bob_dump_bindings) as
`0xSC,shiftstate,actionvalue` lines, actionvalue = KeyName index * 2 (SRC/H/KEYMAPS.H).
Shift states are the KeyName numbers of the KeySrc_BN_* modifier actions (currshifts = index>>1):
in BoB 1 extsh, 2 AltL, 3 CtrlL, 4 ShiftL, 5 Msg, 6 ShMsg, 7 Overlay. Each state is named here by
the key(s) the live table binds to that modifier action, so nothing about them is assumed.
Codes >= 256 are controller inputs (KEYMAPS.H Raw_A<n>_*).
Usage: bob_keymap.py dump.txt SRC/H/KEYMAPS.H > KEYMAP.md
"""
import re, sys, collections

DIK = {0x01:'Esc',0x02:'1',0x03:'2',0x04:'3',0x05:'4',0x06:'5',0x07:'6',0x08:'7',0x09:'8',0x0A:'9',
0x0B:'0',0x0C:'-',0x0D:'=',0x0E:'Backspace',0x0F:'Tab',0x10:'Q',0x11:'W',0x12:'E',0x13:'R',0x14:'T',
0x15:'Y',0x16:'U',0x17:'I',0x18:'O',0x19:'P',0x1A:'[',0x1B:']',0x1C:'Enter',0x1D:'LCtrl',0x1E:'A',
0x1F:'S',0x20:'D',0x21:'F',0x22:'G',0x23:'H',0x24:'J',0x25:'K',0x26:'L',0x27:';',0x28:"'",0x29:'`',
0x2A:'LShift',0x2B:'\\',0x2C:'Z',0x2D:'X',0x2E:'C',0x2F:'V',0x30:'B',0x31:'N',0x32:'M',0x33:',',
0x34:'.',0x35:'/',0x36:'RShift',0x37:'Num*',0x38:'LAlt',0x39:'Space',0x3A:'CapsLock',0x3B:'F1',
0x3C:'F2',0x3D:'F3',0x3E:'F4',0x3F:'F5',0x40:'F6',0x41:'F7',0x42:'F8',0x43:'F9',0x44:'F10',
0x45:'NumLock',0x46:'ScrollLock',0x47:'Num7',0x48:'Num8',0x49:'Num9',0x4A:'Num-',0x4B:'Num4',
0x4C:'Num5',0x4D:'Num6',0x4E:'Num+',0x4F:'Num1',0x50:'Num2',0x51:'Num3',0x52:'Num0',0x53:'Num.',
0x56:'<>',0x57:'F11',0x58:'F12',0x9C:'NumEnter',0x9D:'RCtrl',0xB5:'Num/',0xB7:'PrintScreen',
0xB8:'AltGr',0xC5:'Pause',0xC7:'Home',0xC8:'Up',0xC9:'PgUp',0xCB:'Left',0xCD:'Right',0xCF:'End',
0xD0:'Down',0xD1:'PgDn',0xD2:'Insert',0xD3:'Delete',0xDB:'LWin',0xDC:'RWin',0xDD:'Apps'}

hdr = open(sys.argv[2], encoding='latin-1').read().splitlines()
RAW, desc, order, index = {}, {}, [], {}
for ln in hdr:
    m = re.search(r'Raw_A(\d)_([Ff]ire|b\d+|hat\d[NSEW]{1,2})\s*=\s*(\d+)', ln)
    if m:
        dev, what, code = m.group(1), m.group(2), int(m.group(3))
        what = 'trigger' if what.lower() == 'fire' else ('button ' + what[1:]) if what[0] == 'b' else 'hat %s %s' % (what[3], what[4:])
        RAW.setdefault(code, 'Ctl%s %s' % (dev, what))
    m = re.search(r'Raw_H(\d)_([NSEW]{1,2})\s*=\s*(\d+)', ln)
    if m:
        RAW.setdefault(int(m.group(3)), 'Hat%s %s' % (m.group(1), m.group(2)))
    m = re.match(r'^(?:/\*\*/)?\s*KeyName\(\s*(\d+)\s*,\s*(\w+)\s*\)\s*(?:/\*(.*?)\*/)?', ln)
    if m and int(m.group(1)) not in index:
        index[int(m.group(1))] = m.group(2); desc[m.group(2)] = (m.group(3) or '').strip(); order.append(m.group(2))

live = collections.OrderedDict()          # action -> {scancode: [states]}
modkeys = collections.defaultdict(set)    # modifier index -> scancodes bound to it in state 0
unknown = 0
for ln in open(sys.argv[1]):
    m = re.match(r'^0x([0-9A-Fa-f]+),(\d+),(\d+)', ln)
    if not m: continue
    sc, st, val = int(m.group(1), 16), int(m.group(2)), int(m.group(3))
    name = index.get(val >> 1)
    if name is None: unknown += 1; name = 'value_%d' % val
    if name.startswith('KeySrc_') and st == 0: modkeys[val >> 1].add(sc)
    live.setdefault(name, collections.OrderedDict()).setdefault(sc, []).append(st)

def keyname(sc): return DIK.get(sc, RAW.get(sc, '0x%02X' % sc))
STATE = {}
for i in range(1, 8):
    keys = sorted(modkeys.get(i, ()))
    lab = '/'.join(keyname(k) for k in keys) if keys else '[%s]' % index.get(i, 'state%d' % i)
    STATE[i] = {'LAlt/AltGr': 'Alt', 'LCtrl/RCtrl': 'Ctrl', 'LShift/RShift': 'Shift'}.get(lab, lab)

acts = [a for a in order if a in live and not a.startswith('KeySrc_')] + [a for a in live if a not in desc]
n = sum(len(s) for a in acts for s in live[a].values())  # all table entries
print('# Battle of Britain keyboard map\n')
print('Generated by `tools/bob_keymap.py` from the game\'s own live key table (`BOB_DUMP_BINDINGS`, read')
print('after `Reg3dConv` loads it) and the action list in `SRC/H/KEYMAPS.H`. %d actions, %d key+state bindings.' % (len(acts), n))
print('Program data, not documentation: where a manual disagrees, this wins.\n')
print('**Modifier states.** BoB keeps one modifier state at a time; each is named below by the key(s) the')
print('live table binds to it:\n')
print('| State | KEYMAPS.H action | Key(s) |\n|---|---|---|')
for i in range(1, 8): print('| %d | `%s` | %s |' % (i, index.get(i, '?'), STATE[i]))
print('\n**Linux port keys** (ahead of the table): Ctrl+Esc quits immediately (`SRC/compat/bob_video.cpp`).\n')
# Reachability (STUB3D.CPP OnKeyDown/OnKeyUp): currshifts is set only when a key whose state-0 action
# is a KeySrc modifier is pressed, and cleared on its release. The code that entered Msg/ShMsg is
# //DeadCode AMM 27Jul00. So only state 0 and states that have a live modifier key can ever be current.
REACH = {0} | {i for i in modkeys}
BDG = {272: 'Padlock enemy at screen centre (BDG "S")', 273: 'WinAmp previous track (BDG)',
       274: 'WinAmp start music (BDG)', 275: 'WinAmp stop music (BDG)', 276: 'WinAmp next track (BDG)',
       277: 'WinAmp volume up (BDG)', 278: 'WinAmp volume down (BDG)', 281: 'Other-aircraft view (BDG)',
       282: 'Roving camera (BDG)', 283: 'Roving camera faster (BDG)', 284: 'Roving camera slower (BDG)',
       285: 'Roving camera stop/reset (BDG)', 286: 'Autopilot toggle (BDG)'}
dead_state, no_handler = [], []
print('| Keys | Action | Description |\n|---|---|---|')
for a in acts:
    keys = []
    for sc, states in live[a].items():
        for s in sorted(set(states)):
            k = (STATE[s] + '+' if s else '') + keyname(sc)
            if s not in REACH: dead_state.append((k, a)); continue
            keys.append(k)
    if a.startswith('value_'):
        no_handler.append((keys, a)); continue
    if keys:
        print('| %s | `%s` | %s |' % (', '.join(keys).replace('|', '\\|'), a, desc.get(a, '').replace('|', '\\|')))
print('\n## Bindings with no handler in this program (%d actions)\n' % len(no_handler))
print('The live table binds these keys, but their action index has no `KeyName` in KEYMAPS.H, so no code can')
print('test for them. Indices 272-286 are the BDG 0.99 additions (named from the BDG manual\'s new-key list);')
print('their features are not in this source tree.\n')
print('| Keys | Index | BDG meaning |\n|---|---|---|')
for keys, a in no_handler:
    i = int(a.split('_')[1]) // 2
    print('| %s | %d | %s |' % (', '.join(keys) or '(unreachable state only)', i, BDG.get(i, '')))
print('\n## Bindings in modifier states the running code can never enter (%d)\n' % len(dead_state))
print('States %s have no live modifier key: Rowan removed the code that entered Msg/ShMsg (`//DeadCode AMM' % sorted(set(range(8)) - REACH))
print('27Jul00`, STUB3D.CPP). These table entries are inert; listed for completeness.\n')
print(', '.join('%s → `%s`' % (k, a) for k, a in dead_state))
print('\n## Actions in KEYMAPS.H with no key in the live table\n')
print(', '.join('`%s`' % a for a in order if a not in live and not a.startswith(('KeySrc_', 'Reserved'))))
if unknown: print('\n%d dump values had no KeyName entry (listed as `value_N`).' % unknown)
